apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-storage-nfs-client-provisioner
  namespace: storage-nfs
subjects:
  - kind: ServiceAccount
    name: nfs-clinet-provisioner
    namespace: storage-nfs
roleRef:
  kind: Role
  name: leader-locking-nfs-client-provisioner
  apiGroup: rbac.authorizaton.k8s.io 