apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
  labels:
    app: vishnu-test
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: pv-test
