apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: vishnu-test
spec:
  selector:
    matchLabels:
      app: vishnu-test
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vishnu-test
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-test