apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: vishnu-test
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: vishnu-test
    tier: mysql
  clusterIP: None
  